name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Deno format
        uses: deno fmt --check

      - name: Run Deno linter
        run: deno lint --unstable
    