name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Run Linter
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
